### ISSUE TITLE
Discord Invite Code is Case Sensitive

### ISSUE THREAD

**Issue by MaEtUgR** [tbs-trappy/source_one#1]
As it can be seen from the complete link https://discordapp.com/invite/ZJGkHwF copied from the readme https://github.com/tbs-trappy/source_one/blame/master/README.md#L23 the invite code for the dicord discussion server is case sensitive.

The presumably the same code in the bottom right corner of the "wallpaper" https://github.com/tbs-trappy/source_one/blob/master/photos/sourceone_wallpaper.jpg which was also posted on instagram is all upper case and therefore noone following the short instructions will be able to join with it (I tried).

I suggest to make the lower case letters `k` and `w` not only lower case shape but also a lot smaller to stress the case sensitivity.

By the way super nice project! Looking forward to be involved.

**Comment by ps915** [comment]
Thanks, we will correct it as soon as possible!
