### ISSUE TITLE
Why is this frame so heavy? 

### ISSUE THREAD

**Issue by daimondgeezer** [tbs-trappy/source_one#12]
Is there any way to get this frame lighter? I like everything about it except the weight.

**Comment by ps915** [comment]
Our goal was to build a strong frame, so we didn't really care so much about the weight. Of course there are plenty of things we could do, to save some weight, but we may have to remove some features and thinner some plates. 

If you have any idea on saving weight, tell us and we can talke about it.

**Comment by daimondgeezer** [comment]
Thanks for your reply. I plan to use this frame as my next build. Will probably get rid of the camera mounting plate and slam it with some lower standoffs.

**Comment by tobiasbischoff** [comment]
I recently build one and was thinking the same. There is a ton of Carbon in it. The Bottom Plate and the lower Sandwich plate are probably too thick. You could probably get away with much thinner plates out of high quality carbon here. I would not recommend getting rid of the camera plates, the add a lot of structural integrety in the front. I would rather switch to aluminium hardware in the non structural areas.

**Comment by daimondgeezer** [comment]
Thanks a lot for your input. Will give this frame a go after I break the next boomerang arm on my Flosstyle. It looks like a tank 🙂

**Comment by fpvg** [comment]
well i can attest. I bought this frame thinking it was going to be better. And it hasn"t broke yet, some scuffs on the arms from concrete i see a arm delaming on the edge but hell, this thing has been to hell and back far more than my old lighter clone frame, and still going strong tell this day. in the begining , everything breaks but this frame, lol. not that it cant be broken , but man id pay to see that. maybe ill make a video challenge

**Comment by fpvg** [comment]
leave it alone for us, bashers, make a lighter race version for the speed junkies,lol
