### ISSUE TITLE
Sticky Pad Doesn't Fit Correctly

### ISSUE THREAD

**Issue by drlocke** [tbs-trappy/source_one#17]
The sticky pad has two cavities for the two screws on the top plate. These cavities no longer correspond to the position of the screws in v3. At least not if one assumes that the cut-out pattern of the sticky pad should correspond to that of the top plate.

**Comment by ps915** [comment]
When we released V3, TBS did not grabbed the new file for our new battery pad. So they produced the wrong one. 

But: you can use those battery pads, anyway. Just make new cutouts for screws (red circles)
![67573308_2552959591382906_2544169795280961536_n](https://user-images.githubusercontent.com/3420935/66852785-0298d900-ef7e-11e9-840d-ea010555b135.jpg)
