### ISSUE TITLE
Cutting

### ISSUE THREAD

**Issue by mpbgodinho** [tbs-trappy/source_one#18]
I have a CNC machine, wich is the best milling cutter to DIY the frame?

Many thanks

**Comment by ps915** [comment]
I don't have any CNC cutter at home but had the chance to lean CNC cutting a bit during my job. 
Diameter of the milling tool: check the files and search for the smallest inner radius. Thats your diameter for the milling tool. Outer radius can of yours be milled with lager tools, but then you have to change tools of course.

i used these tools for carbon fibre: http://www.brokking.net/images/carbon_fiber/carbon_fiber_04.jpg
