### ISSUE TITLE
Name of Frame

### ISSUE THREAD

**Issue by ObstacleTAKUYA** [tbs-trappy/source_one#20]
Hello,
im currently working on a complete Rework of the Frame. Less High, built in gopro mount and so on. 
When its done, id like to sell it on armattan Productions or even manufacture it myself. Am I allowed to do that and name the Frame something like  "Takuya´s NAME " or does it have to be Takuya´s Source One Version X.X
Cheers

**Comment by tbs-trappy** [comment]
if there is no resemblance you can call it whatever, as long as attribution is given. if it's exactly the same thing, then the SOURCE ONE name should prevail.

**Comment by ObstacleTAKUYA** [comment]
okey great! one thing i need to ask though. Where can i get these pressnuts from?
Do you know if armattan productions has these?
