### ISSUE TITLE
No documentation for V4 assembly

### ISSUE THREAD

**Issue by Matthew-Beckett** [tbs-trappy/source_one#23]
There is no documentation for assembly of the V4 frame.

**Comment by ps915** [comment]
What is your question regarding the assembly?

**Comment by Matthew-Beckett** [comment]
Hi Phillipp,

I am experiencing not necessarily an issue but a concern with how the V4 sandwich plate mounts to the bottom plate. The shorter M3 screws supplied with the retail variant only expose a minimal amount of thread for my flight controller standoffs to mount to, I am concerned this will break free in flight or in a crash.

Furthermore, switching to using the larger screw results in too much thread being exposed above the bottom plate and the anti-vibration standoffs not sitting flush with the frame.

Also, since the redesign of the sandwich plate, I am confused about the use of the two most central threaded posts. Do I use these to secure the plate further to the bottom? My stack is 30.5mm and at the moment my arms are only secured with the outermost screws into the threaded inserts as the inner ones are not threaded and I can only assume is used by the long M3 screws to mount a smaller flight stack.

However, all of this speculation as to how it goes together, what each mounting hole is for, and which screws to use during my first build has led to quite a lot of frustration and considering the assembly of the V3 variant was quite well documented I am disappointed the same love has not been given to the redesigned variant. 

Especially when it's so different to a noob like me from previous iterations. If I was to follow the V3 instructions for mounting the sandwich plate and arms I would have one screw per arm secured in the threaded insert and the second screw would just be push fit into the bottom plate's hole and held in by nothing more than friction.

**Comment by krunked-fpv** [comment]
long screws on outside, shorer on inside, use nylon standoff. done.

**Comment by Matthew-Beckett** [comment]
Do I still need the shorter on the inside with a 30.5mm stack? There's nothing for the inner ones to thread into, and the longer ones push the standoffs too high which came with my F405-STD

**Comment by krunked-fpv** [comment]
nope just use long ones on the outside and screw in nylong standoffs. use
short ones on center.
my s1 v4 is slammed to 20mm and i have plenty of room.

**Comment by Matthew-Beckett** [comment]
@ps915 would you accept a PR with V4 instructions? @krunked-fpv thank you so much!
