### ISSUE TITLE
Camera screw hole too large

### ISSUE THREAD

**Issue by drdrenz** [tbs-trappy/source_one#3]
Camera hole is 3.8mm in diameter, would be better is it was 2mm.  updated design attached to rectify.
[SOURCE ONE camera hole 2mm.zip](https://github.com/tbs-trappy/source_one/files/2350220/SOURCE.ONE.camera.hole.2mm.zip)

**Comment by ps915** [comment]
thanks for your submission. We already changef this in the next version (0.2) which will be released in a few days. 

I will close the issue, but keep your file online if anyone wants to download it.
