### ISSUE TITLE
Source One Killa Drone Arms

### ISSUE THREAD

**Issue by drdrenz** [tbs-trappy/source_one#4]
Modified Arms to allow for better motor protection for larger motors
[SOURCE ONE Killa Drones 5.5 inch arms.zip](https://github.com/tbs-trappy/source_one/files/2350236/SOURCE.ONE.Killa.Drones.5.5.inch.arms.zip)
 and to allow for my favorite props size 5.5 inch...

**Comment by ps915** [comment]
thanks for your submission. We already changef this in the next version (0.2) which will be released in a few days. 

I will close the issue, but keep your file online if anyone wants to download it.
