### ISSUE TITLE
Possibility or problems with making a "slammed" ? 

### ISSUE THREAD

**Issue by sense-amr** [tbs-trappy/source_one#7]
Since these really low CG rigs are all the go these days .. and i have to admit i really enjoy my alien 5" "slammed" .. i was wondering if there is any structural issues regarding the frame .. to using shorter standoffs to make a slammed Source?

**Comment by ps915** [comment]
You will loose the ability to use the camera plates which are also a stuctural part. I dont think there are structural issues when you use smaller standoffs and use long screws for the first 4 standoffs! 

Feel free to report back your findings, if you use the frame "slammed"

**Comment by sense-amr** [comment]
Ahh .. will that camera mount support an HS1177?

**Comment by ps915** [comment]
Yes, but not when you have smaller standoffs

**Comment by sense-amr** [comment]
i might have to make an issue to have the frame support .. Slammed Standoffs.. and have an alternative camera mount made for it :)

**Comment by sense-amr** [comment]
are you flying a source one? ..
