### ISSUE TITLE
add "were to buy"

### ISSUE THREAD

**Issue by tedelm** [tbs-trappy/source_one#9]
https://www.skanehobby.se/shop/tbs-source-one-v0-2/

**Comment by juampifpv** [comment]
Hi, how are you? I have eShop in my country ARGENTINA and i sell several thing for TBS and Source ONE too. I want to be in the shopping list.
Thanks a lot!

Link https://www.juampifpv.com

Juampi

**Comment by ps915** [comment]
done and done! ;)
